-- MIGRATION: Player FIFA Stats (v8)
-- Adding FIFA-style stats to the players table

ALTER TABLE players ADD COLUMN IF NOT EXISTS country TEXT DEFAULT 'FR';
ALTER TABLE players ADD COLUMN IF NOT EXISTS stats_pac INTEGER DEFAULT 50;
ALTER TABLE players ADD COLUMN IF NOT EXISTS stats_sho INTEGER DEFAULT 50;
ALTER TABLE players ADD COLUMN IF NOT EXISTS stats_pas INTEGER DEFAULT 50;
ALTER TABLE players ADD COLUMN IF NOT EXISTS stats_dri INTEGER DEFAULT 50;
ALTER TABLE players ADD COLUMN IF NOT EXISTS stats_def INTEGER DEFAULT 50;
ALTER TABLE players ADD COLUMN IF NOT EXISTS stats_phy INTEGER DEFAULT 50;
ALTER TABLE players ADD COLUMN IF NOT EXISTS stats_overall INTEGER DEFAULT 50;

-- Comment for clarity
COMMENT ON COLUMN players.country IS 'ISO country code (e.g., FR, BE, ES)';
